# Generated by Django 3.2 on 2021-06-01 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('storeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclaims',
            name='userid',
            field=models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userlogins',
            name='userid',
            field=models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.DeleteModel(
            name='Userroles',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
