# Generated by Django 3.2 on 2021-06-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0004_auto_20210603_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='name',
            field=models.CharField(db_column='Name', max_length=60, unique=True),
        ),
    ]
