# Generated by Django 3.2 on 2021-06-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0006_auto_20210604_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookcategory',
            options={'managed': True, 'verbose_name': '图书类别', 'verbose_name_plural': '图书类别'},
        ),
        migrations.RemoveField(
            model_name='books',
            name='imgpath',
        ),
        migrations.AddField(
            model_name='books',
            name='click_count',
            field=models.IntegerField(default=0, verbose_name='点击量'),
        ),
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='books/image', verbose_name='封面图'),
        ),
        migrations.AddField(
            model_name='books',
            name='sold_count',
            field=models.IntegerField(default=0, verbose_name='销量'),
        ),
        migrations.AddField(
            model_name='books',
            name='stock_count',
            field=models.IntegerField(default=100, verbose_name='库存量'),
        ),
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.CharField(db_column='Description', max_length=1000, verbose_name='图书描述'),
        ),
        migrations.AlterField(
            model_name='books',
            name='name',
            field=models.CharField(db_column='Name', max_length=60, unique=True, verbose_name='书名'),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.DecimalField(db_column='Price', decimal_places=2, max_digits=10, verbose_name='价格'),
        ),
    ]
