# Generated by Django 3.2 on 2021-06-04 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0007_auto_20210604_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='resources/book_image', verbose_name='封面图'),
        ),
    ]
