# Generated by Django 3.2 on 2021-06-06 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0008_alter_books_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userclaims',
            name='userid',
        ),
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.ForeignKey(db_column='BookCategory_Id', on_delete=django.db.models.deletion.CASCADE, to='storeApp.bookcategory', verbose_name='类别'),
        ),
        migrations.DeleteModel(
            name='Orderdetails',
        ),
        migrations.DeleteModel(
            name='Orderheaders',
        ),
        migrations.DeleteModel(
            name='Userclaims',
        ),
    ]
