# Generated by Django 3.2 on 2021-06-06 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0009_auto_20210606_2152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'managed': True, 'verbose_name': '图书信息', 'verbose_name_plural': '图书信息'},
        ),
    ]
