# Generated by Django 3.2 on 2021-06-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0010_alter_books_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcategory',
            name='name',
            field=models.CharField(db_column='Name', max_length=20, verbose_name='类别名'),
        ),
    ]
