# Generated by Django 3.2 on 2021-06-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='is_signed',
            field=models.BooleanField(default=False, verbose_name='签收状态'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='memo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='订单备注'),
        ),
    ]
