# Generated by Django 3.2 on 2021-06-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20210606_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='amount_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='订单总金额'),
        ),
    ]
