# Generated by Django 3.2 on 2021-06-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_alter_orderinfo_amount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='order_sn',
            field=models.IntegerField(null=True, verbose_name='订单编号'),
        ),
    ]
