# Generated by Django 3.2 on 2021-06-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_orderinfo_order_sn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_sn',
            field=models.CharField(default=0, max_length=20, verbose_name='订单编号'),
            preserve_default=False,
        ),
    ]
