# Generated by Django 3.2 on 2021-06-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_alter_orderinfo_order_sn'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='now_available',
            field=models.BooleanField(default=True, verbose_name='现在库存量充足'),
        ),
    ]
